# Generated by Django 5.0 on 2023-12-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_service_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatrehall',
            old_name='seat_in_row',
            new_name='seats_in_row',
        ),
        migrations.AddField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='theatre_service_app.performance'),
            preserve_default=False,
        ),
    ]
