# Generated by Django 5.0 on 2023-12-12 00:01

import theatre_service_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_service_app', '0003_alter_performance_options_alter_play_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to=theatre_service_app.models.play_image_file_path),
        ),
    ]
